---
- name: Prepare Podman images
  hosts: ipv6
  become: true
  tasks:
  - name: Copy Podman images files to server
    ansible.posix.synchronize:
      src: images
      dest: /tmp
      compress: yes
  - name: Import Podman Images
    containers.podman.podman_load:
      input: "{{ item }}"
    loop:
      - /tmp/images/ipv6-base.tar
