---
- name: Register machine in DNS
  hosts: kea
  become: true
  tasks:
  - name: Copy DNS key files to server
    template: src="{{ item }}" dest="/tmp" owner="root" group="root" mode="0440"
    loop:
      - dane.key
      - nsupdate.script
  - name: Firewalld - permit traffic in default zone for DNS
    ansible.posix.firewalld:
     service: dns
     permanent: yes
     state: enabled
    notify: "kick_firewalld"
  - name: Create DNS entries
    command: nsupdate -k /tmp/dane.key /tmp/nsupdate.script
  handlers:
  - name: Restart Cockpit service
    listen: kick_cockpit
    service:
        name: "cockpit"
        state: restarted
  - name: Restart Firewalld service
    listen: kick_firewalld
    service:
        name: "firewalld"
        state: restarted
- name: Install ACME Cert
  hosts: kea
  become: true
  tasks:
    - name: stop Firewall
      service: name="firewalld" enabled="yes" state="stopped"
    - name: Clone ACME.SH
      git: repo="https://github.com/Neilpang/acme.sh" dest="/root/acme.sh"
    - name: Get Certificate
      shell: "/root/acme.sh/acme.sh --issue  -d kea{{ ansible_hostname[-3:] }}.dane.onl  --standalone --server letsencrypt"
      ignore_errors: yes
      args:
        creates: "/root/.acme.sh/kea{{ ansible_hostname[-3:] }}.dane.onl_ecc/kea{{ ansible_hostname[-3:] }}.dane.onl.cer"
    - name: start Firewall
      service: name="firewalld" enabled="yes" state="started"
    - name: set Certificate for Cockpit
      shell: "setenforce 0 && rm -f /etc/cockpit/ws-certs.d/* && /usr/bin/cp /root/.acme.sh/kea{{ ansible_hostname[-3:] }}.dane.onl_ecc/kea{{ ansible_hostname[-3:] }}.dane.onl.cer /etc/cockpit/ws-certs.d/0-self-signed.cert && /usr/bin/cp /root/.acme.sh/kea{{ ansible_hostname[-3:] }}.dane.onl_ecc/kea{{ ansible_hostname[-3:] }}.dane.onl.key /etc/cockpit/ws-certs.d/0-self-signed.key"
    - name: Adjust Cert permissions
      shell: "chmod 640 /etc/cockpit/ws-certs.d/*.cert && chown root:cockpit-ws /etc/cockpit/ws-certs.d/*.cert"
- name: cleanup
  hosts: kea
  become: true
  tasks:
    - name: Clean DANE Key
      file: state="absent" path="/tmp/dane.key"
    - name: Clean nsupdate script
      file: state="absent" path="/tmp/nsupdate.script"
