---
- name: Prepare Podman images
  hosts: kea
  become: true
  tasks:
#  - name: Copy Podman images files to server
#    ansible.posix.synchronize:
#      src: "{{ item }}"
#      dest: /tmp
#      compress: yes
#    loop:
#      - images/bind.tar
  - name: Import BIND9 Image
    shell: "podman rmi bind; podman import /tmp/bind.tar bind9"
